os: Visual Studio 2015
platform: x64
configuration: Release
shallow_clone: true
install:

# Setup shell for VS2015, x64
  - call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
# Set path to python, git-bash tools.
  - "set PATH=C:\\Python35-x64;C:\\Python35-x64\\Scripts;%PATH%"
  - "set PATH=C:\\Program Files (x86)\\Git\\bin;%PATH%"
  - pip install pytest
  - pip install numpy
  - pip install cython

# Use cclash for compiler caching (experimental)
  - ps: wget https://github.com/inorton/cclash/releases/download/0.3.14/cclash-0.3.14.zip -OutFile cclash-0.3.14.zip
  - ps: 7z x cclash-0.3.14.zip
  - "set PATH=%APPVEYOR_BUILD_FOLDER%\\cclash-0.3.14;%PATH%"
  - "set CCLASH_DIR=C:\\ProgramData\\cclash"

# Download FFTW3 for PME plugin
  - C:\MinGW\msys\1.0\bin\wget -q ftp://ftp.fftw.org/pub/fftw/fftw-3.3.4-dll64.zip
  - 7z x fftw-3.3.4-dll64.zip -oC:\fftw > null
  - cd C:\fftw
  - lib /def:libfftw3f-3.def
  - cd %APPVEYOR_BUILD_FOLDER%
  - "set PATH=C:\\fftw;%PATH%"

# Download and install some OpenMM build dependencies (doxygen, swig)
  - choco install -y doxygen.install swig > null

# Download OpenCL Headers and build the ICD loader
  - ps: "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;"
  - ps: $opencl_registry = "https://www.khronos.org/registry/cl"
  - ps: $opencl_github = "KhronosGroup/OpenCL-Headers"
  - ps: mkdir C:/opencl > $null
  - ps: cd C:/opencl
  - ps: wget $opencl_registry/specs/opencl-icd-1.2.11.0.tgz -OutFile opencl-icd-1.2.11.0.tgz
  - ps: 7z x opencl-icd-1.2.11.0.tgz > $null
  - ps: 7z x opencl-icd-1.2.11.0.tar > $null
  - ps: mv .\icd\* .
  - ps: mkdir inc/CL > $null
  - ps: wget https://github.com/$opencl_github/tree/master/CL -UseBasicParsing | select -ExpandProperty links | where {$_.href -like "*.h*"} | select -ExpandProperty title | foreach{ wget https://raw.githubusercontent.com/$opencl_github/master/CL/$_ -OutFile inc/CL/$_ -UseBasicParsing}
  - ps: mkdir lib > $null
  - ps: cd lib
  - cmake -G "NMake Makefiles" ..
  - nmake
  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  - ps: $env:CMAKE_FLAGS =
      "-DOPENMM_BUILD_PME_PLUGIN=ON
       -DOPENCL_INCLUDE_DIR=C:/opencl/inc
       -DOPENCL_LIBRARY=C:/opencl/lib/OpenCL.lib
       -DFFTW_LIBRARY=C:/fftw/libfftw3f-3.lib
       -DFFTW_INCLUDES=C:/fftw
       -DOPENMM_BUILD_EXAMPLES=OFF
       -DOPENMM_BUILD_OPENCL_TESTS=OFF
       -DCMAKE_BUILD_TYPE=Release
       -LA"
  - mkdir build
  - cd build
  - cmake -G "NMake Makefiles" %CMAKE_FLAGS% -DCMAKE_CXX_FLAGS_RELEASE="/MD /Od /Ob0 /D NDEBUG" ..
  - cmake --build . --target install
  - cmake --build . --target PythonInstall

test_script:
  - python %APPVEYOR_BUILD_FOLDER%\devtools\run-ctest.py
  - cd python\tests
  - py.test -v

cache:
- C:\ProgramData\cclash -> appveyor.yml
